### ISSUE TITLE
 Multiple Buckets under YML, Resouce

### ISSUE THREAD

**Issue by ajshukury** [matt-filion/s3-db#20]
When listing multiple buckets to deal with under the resource, they don't end up the policy so  I get permission denied. How can multiple buckets be used like below?
```
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::bucket1*"
           - - "arn:aws:s3:::bucket2*"
           - - "arn:aws:s3:::bucket2*"
```
